### ISSUE TITLE
请问雷电三驱动了吗

### ISSUE THREAD

**Issue by zf1976** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#15]
<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by wjz304** [comment]
接口可用，速度你自己测试吧



Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年8月5日(星期四) 下午2:06
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 请问雷电三驱动了吗 (#15)





 
Sent from PPHub
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
