### ISSUE TITLE
12 b7 雷电3貌似不能热插拔了

### ISSUE THREAD

**Issue by AugustToko** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#18]
👀

**Comment by wjz304** [comment]
没出现啊？怎么操作的？

**Comment by AugustToko** [comment]
> 没出现啊？怎么操作的？

启动后重新插拔雷电扩展坞 然后没法识别，得重启系统

**Comment by wjz304** [comment]
最新的efi吗？ 印象中 bios 中有个设置。



Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 12 b7 雷电3貌似不能热插拔了 (#18)





  
没出现啊？怎么操作的？
  
�启动后重新插拔雷电扩展坞 然后没法识别，得重启系统
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by AugustToko** [comment]
> 印象中 bios 中有个设置

ok 我晚点研究一下， 如果方便看看你的bios雷电设置呢 👀

**Comment by wjz304** [comment]
Settings\高级\Intel (R) Thunderbolt
  SW SMI on TBT hot-plug
  ACPI Notify on TBT Hot-plug

**Comment by AugustToko** [comment]
> Settings\高级\Intel (R) Thunderbolt SW SMI on TBT hot-plug ACPI Notify on TBT Hot-plug

感谢 晚点试试 这两天机子不在边上，先 close 了
