### ISSUE TITLE
大佬好，小白有两个疑问

### ISSUE THREAD

**Issue by yangxingyu0315** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#19]
1

**Comment by wjz304** [comment]
你可以参照说明中的型号对比一下，
usb需要定制，其他基本都通用，
网卡型号要看一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月9日(周二) 下午5:24
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 大佬好，小白有两个疑问 (Issue #19)




 
我的配置是i7-10700k + MSI Z490 Gaming Carbon WiFi + 盈通6800XT + BCM94360CD
 
1.用您的efi，是否能安装Monterey12.0.1 ？安装后有没有不好用的地方，如蓝牙wifi短连？
 2.如安装big sur，我的配置能否契合您的efi ？
 3.妙控触摸板是否支持 ？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
