### ISSUE TITLE
你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了

### ISSUE THREAD

**Issue by zzjzkf** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#21]
ax201没法驱动

**Comment by wjz304** [comment]
12.1b 目前 WIFI 和 BT 是有问题， 12.0.1 应该是可以的。
等待 zxystd 大神修复中

**Comment by wjz304** [comment]
12.1b   wifi 有概率，bt 发现设备也连不上

**Comment by wjz304** [comment]
12.1 现在蓝牙还不好使， WIFI有概率， 12.0.1 应该是好使的(最近比较忙，记不清了)






Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 下午3:25
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21)





 
ax201没法驱动
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzjzkf** [comment]
谢谢，坐等大佬更新

**Comment by zzjzkf** [comment]
> 12.1b wifi 有批评，bt 发现设备也连不上

大佬，看你更新wifi驱动了，但是好像还是不能用

**Comment by wjz304** [comment]
尝试：
关机断电，长按开机键5秒，接电源，开机， ---- 来自远景




Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月18日(星期六) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21)





  
12.1b wifi 有批评，bt 发现设备也连不上
  
大佬，看你更新wifi驱动了，但是好像还是不能用
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzjzkf** [comment]
> 尝试： 关机断电，长按开机键5秒，接电源，开机， ---- 来自远景 Ing... &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wjz304/Hackintosh-EFI-MSI-Z490i-Unify" ***@***.***&gt;; 发送时间:&nbsp;2021年12月18日(星期六) 下午2:43 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21) 12.1b wifi 有批评，bt 发现设备也连不上 大佬，看你更新wifi驱动了，但是好像还是不能用 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***&gt;

刚试过好几次了，还是不行。放弃了。。。大佬的能正常驱动吗？

**Comment by wjz304** [comment]
能连音响&nbsp;

Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年12月18日(星期六) 下午3:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21)





  
尝试： 关机断电，长按开机键5秒，接电源，开机， ---- 来自远景 Ing... &nbsp;
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "wjz304/Hackintosh-EFI-MSI-Z490i-Unify" @.&gt;; 发送时间:&nbsp;2021年12月18日(星期六) 下午2:43 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21) 12.1b wifi 有批评，bt 发现设备也连不上 大佬，看你更新wifi驱动了，但是好像还是不能用 — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: @.***&gt;
  
刚试过好几次了，还是不行。放弃了。。。大佬的能正常驱动吗？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzjzkf** [comment]
可以连接音响，这些都正常，就差蓝牙跟wifi驱动不了。我是6600xt显卡

**Comment by wjz304** [comment]
额， 我的意思是我的可以连蓝牙音箱， 但是android 连不上， iphone没试
wifi 大部分时候正常。偶尔驱动不了重启就好了



Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月18日(星期六) 下午3:57
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 你好，我跟你一样的主板，但是我网卡不知道为什么驱动不了 (Issue #21)





 
可以连接音响，这些都正常，就差蓝牙跟wifi驱动不了。我是6600xt显卡
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by zzjzkf** [comment]
蓝牙可以用了，差WiFi了，好尴尬
