### ISSUE TITLE
大神好，有2个问题希望能够帮助下

### ISSUE THREAD

**Issue by sonken87** [wjz304/Hackintosh-EFI-MSI-Z490i-Unify#22]
1.用小军刀看蓝牙信息，在厂商这块显示的是？？？，不是大神截图的intel
2.最近显卡换成6600xt蓝宝石超白金，苹果logo引导到一半就黑屏了，过个半分钟以后可以正常点亮，请问如何解决
希望大佬能够解答一下，谢谢

**Comment by wjz304** [comment]
1.截图是 bigsur的， 12.1 现在蓝牙还不好使， 12.0.1 应该是好使的(最近比较忙，记不清了)
2.好像没什么办法， 我一直用的啰嗦模式。得空研究下




Ing...


&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "wjz304/Hackintosh-EFI-MSI-Z490i-Unify"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月14日(星期天) 晚上9:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[wjz304/Hackintosh-EFI-MSI-Z490i-Unify] 大神好，有2个问题希望能够帮助下 (Issue #22)





 
1.用小军刀看蓝牙信息，在厂商这块显示的是？？？，不是大神截图的intel
 2.最近显卡换成6600xt蓝宝石超白金，苹果logo引导到一半就黑屏了，过个半分钟以后可以正常点亮，请问如何解决
 希望大佬能够解答一下，谢谢
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by sonken87** [comment]
请问大神的电脑是否可以正常睡眠，正常唤醒，用了大神的efi，唤醒总是重启

**Comment by wjz304** [comment]
有人换过N块z490i主板试过，唤醒重启 是主板的问题，
